name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: 'jsbt v0.4.0' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/release.yml@2bb91844d7155bf62deaba2d8a4c53cfe032b59a
    with:
      build-path: test/build
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      contents: write
      id-token: write
      attestations: write
