/** Adds two numbers.
 * Docs: https://example.com/docs/reference/path/that-is-intentionally-long-enough-to-exceed-the-line-limit-for-comment-check
 * @param a - First addend.
 * @param b - Second addend.
 * @returns Sum of both addends.
 * @example
 * Add two numbers.
 * ```ts
 * import { add } from '@jsbt-test/check-root';
 * add(20, 22);
 * ```
 */
/*
 * VeryLongIdentifierNameThatCannotWrapCleanlyInsideABlockCommentBecauseItHasNoWhitespaceAndShouldStayAllowedAsWritten
 */
export const add = (a: number, b: number): number => a + b;

type TRet<T> = T extends (...args: infer A) => infer R
  ? (...args: { [K in keyof A]: A[K] }) => R
  : T;
type BytesFn = (value: Uint8Array) => Uint8Array;
/**
 * Echoes byte input.
 * @param value - bytes to echo
 * @returns The same byte view.
 * @example
 * Echo bytes through a wrapped callable type.
 * ```ts
 * import { wrappedBytes } from '@jsbt-test/check-root';
 * wrappedBytes(new Uint8Array([1, 2, 3]));
 * ```
 */
export const wrappedBytes: TRet<BytesFn> = (value) => value;

/**
 * Doubles byte input.
 * @param value - bytes to double
 * @returns The same byte view.
 * @example
 * Double bytes through docs attached to the wrapped type.
 * ```ts
 * import { aliasDocumented } from '@jsbt-test/check-root';
 * aliasDocumented(new Uint8Array([1, 2, 3]));
 * ```
 */
type AliasDocumented = (value: Uint8Array) => Uint8Array;
export const aliasDocumented: TRet<AliasDocumented> = (value) => value;

/**
 * Creates a wrapped byte function.
 * @param seed - fallback byte value
 * @returns Wrapped byte function.
 * @example
 * Create a wrapped callable return.
 * ```ts
 * import { createWrapped } from '@jsbt-test/check-root';
 * createWrapped(1);
 * ```
 */
export function createWrapped(seed: number): TRet<BytesFn> {
  return (value) => new Uint8Array([value[0] || seed]);
}

/** Byte generator interface. */
export interface Generator {
  /**
   * Generates byte output.
   * @param length - number of bytes to generate
   * @returns Generated bytes.
   */
  randomBytes(length: number): TRet<Uint8Array>;
}
